name: say_chat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.1.2
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  qr_flutter: ^4.1.0  # để tạo QR code
  mobile_scanner: ^5.0.0  # để quét QR code
  permission_handler: ^11.0.0  # xin quyền camera
  image_picker: ^1.0.7  # chọn ảnh/video
  flutter_sound: ^9.2.13  # ghi âm (thay thế record)
  path_provider: ^2.1.2  # lấy đường dẫn lưu file
  socket_io_client: ^3.1.4
  flutter_webrtc: ^1.3.1
  google_sign_in: ^6.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/google2.png
    - assets/icons/
